### ISSUE TITLE
Hoofdgroep is dependent on Enkel/dubbel bestemming

### ISSUE THREAD

**Issue by BakkerJesse** [BakkerJesse/SemanticTeamIMRO#20]
https://github.com/BakkerJesse/SemanticTeamIMRO/blob/b716ecc86fd5bb6b33ddf339a0a077fe00125ded/Models/Specific/Bestemmingsplangebied/shapes.ttl#L205

**Comment by eknutov** [comment]
what is exactly the issue here? could you please provide the detailed description? who are the assignees? it is been hanging here for almost a month here, can we close? resolve it?

**Comment by BakkerJesse** [comment]
The current shape here should be expanded such that "Hoofdgroep is dependent on Enkel/dubbel bestemming". Meaning, given the type of planobject (either `enkel- ` or `dubbelbestemming`), `hoofdgroep` should have a specific range. 

As of now the distinction has not been made.

**Comment by eknutov** [comment]
issue has been moved to the internal Git
