### ISSUE TITLE
GML shapes overcomplicated?

### ISSUE THREAD

**Issue by pmaria** [BakkerJesse/SemanticTeamIMRO#36]
In PR #32 [this discussion](https://github.com/BakkerJesse/SemanticTeamIMRO/pull/32#discussion_r151987046) , and [this one](https://github.com/BakkerJesse/SemanticTeamIMRO/pull/32#discussion_r151987603) were started. Finish here and act accordingly.

**Comment by eknutov** [comment]
issue has been moved to the internal Git
