### ISSUE TITLE
Plans should also be void:Datasets

### ISSUE THREAD

**Issue by pmaria** [BakkerJesse/SemanticTeamIMRO#38]
I think plans should be datasets. And every planobject or tekstobject within a plan should have a void:inDataset triple. This should be added to all relevant shapes.

**Comment by BakkerJesse** [comment]
Plans already are of type `void:dataset`. 
`void:inDataset` should indeed be added.  I can push this shortly to `review`

**Comment by eknutov** [comment]
issue has been moved to the internal Git
